### ISSUE TITLE
Custom Cursor maken en in website zetten

### ISSUE THREAD

**Issue by Annevd** [DamianR2004/your-tribe-for-life-squad-page#11]
## DLC: Analyseren, Ontwerpen & Bouwen

**Comment by Annevd** [comment]
## Analyseren

Om te beginnen heb ik opgezocht hoe en op welke manieren je een custom cursor kan maken voor je website. 
Dit kan blijkbaar op 2 manieren: een image die je via CSS instelt, of door middel van div('s) en Javascript.

Bron: https://www.freecodecamp.org/news/how-to-make-a-custom-mouse-cursor-with-css-and-javascript/ 

Idee: een custom cursor van een verfkwast. De standaard state is een penseel zonder verf, zodra je hovert op een knop of link verschijnt er verf op de verfkwast zodat het nog steeds duidelijk blijft voor de gebruiker dat iets clickable is.

**Comment by Annevd** [comment]
## 10-9 Ontwerpen

Ik heb twee verschillende states voor de custom cursor ontworpen. Een penseel waar geen verf op zit, en voor de hover state hetzelfde penseel maar met verf erop.

**Zero state:**

<img width=400 src="https://github.com/user-attachments/assets/60b57db8-f035-440c-bb59-4a674ca0bafa">

**Hover state:**

<img width=400 src="https://github.com/user-attachments/assets/6afeb518-c2d5-4950-84e7-31d12c6597ae">

**Comment by Annevd** [comment]
## 12-9 Updated version

Het design heb ik iets veranderd naar een wat korter penseel, zodat het wat groter is en beter opvalt:

<img width= 400 src="https://github.com/user-attachments/assets/b95228c4-e78b-4837-a350-8d281581be3a">

Ook hebben Damian en ik het bestand omgezet naar een SVG zodat het niet kwaliteit verliest bij het downscalen.

**Comment by Annevd** [comment]
## 17-9 Implementatie custom cursor

Dit is hoe ik de custom cursor geïmplementeerd heb in de code:

```CSS
body{
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    font-size: 25px;
    overflow-x: hidden;
    cursor: url('../kwast1.svg'), auto;
}

a:hover {
    cursor: url('../kwast2.svg'), auto;
}
```

De SVG's staan in de `/static` map.
